import React, { useState, useEffect } from 'react';
import { Link } from 'react-router-dom';

const Reports = () => {
  const [reports, setReports] = useState([]);
  const [loading, setLoading] = useState(true);

  useEffect(() => {
    fetch('/api/reports')
      .then(res => res.json())
      .then(data => {
        setReports(data.data || []);
        setLoading(false);
      })
      .catch(err => {
        console.error(err);
        setLoading(false);
      });
  }, []);

  return (
    <div className="page-content animate-fade-in">
      <div style={{ display: 'flex', justifyContent: 'space-between', alignItems: 'center', marginBottom: '2rem' }}>
        <div>
          <div style={{ display: 'flex', alignItems: 'center', gap: '0.5rem', fontSize: '0.85rem', color: 'var(--text-muted)', marginBottom: '0.25rem' }}>
            <Link to="/dashboard" style={{ display: 'flex', alignItems: 'center', gap: '0.25rem', color: 'var(--primary)' }}>
              <ion-icon name="home-outline"></ion-icon> Home
            </Link>
            <span>/</span>
            <span>Reports</span>
          </div>
          <h1 style={{ fontSize: '1.75rem', margin: 0 }}> medico-legal Reports Registry</h1>
        </div>
        <button className="btn btn-primary">
          <ion-icon name="print-outline"></ion-icon> Print Selected
        </button>
      </div>

      <div className="glass-panel" style={{ padding: '1.5rem' }}>
        <div style={{ display: 'grid', gridTemplateColumns: '1fr 1fr 1fr', gap: '1rem', marginBottom: '2rem' }}>
          <div style={{ padding: '1.5rem', background: 'rgba(0,0,0,0.2)', borderRadius: 'var(--radius-md)', border: '1px solid var(--border)', textAlign: 'center', cursor: 'pointer' }}>
            <ion-icon name="document-text" style={{ fontSize: '2.5rem', color: 'var(--primary)', marginBottom: '0.5rem' }}></ion-icon>
            <h4 style={{ margin: 0 }}>Medico-Legal Report (MLR)</h4>
            <p style={{ fontSize: '0.85rem', margin: '5px 0 0 0', color: 'var(--text-muted)' }}>Generate clinical court report</p>
          </div>
          <div style={{ padding: '1.5rem', background: 'rgba(0,0,0,0.2)', borderRadius: 'var(--radius-md)', border: '1px solid var(--border)', textAlign: 'center', cursor: 'pointer' }}>
            <ion-icon name="flask" style={{ fontSize: '2.5rem', color: 'var(--accent)', marginBottom: '0.5rem' }}></ion-icon>
            <h4 style={{ margin: 0 }}>Postmortem Report (PMR)</h4>
            <p style={{ fontSize: '0.85rem', margin: '5px 0 0 0', color: 'var(--text-muted)' }}>Generate autopsy report</p>
          </div>
          <div style={{ padding: '1.5rem', background: 'rgba(0,0,0,0.2)', borderRadius: 'var(--radius-md)', border: '1px solid var(--border)', textAlign: 'center', cursor: 'pointer' }}>
            <ion-icon name="stats-chart" style={{ fontSize: '2.5rem', color: 'var(--success)', marginBottom: '0.5rem' }}></ion-icon>
            <h4 style={{ margin: 0 }}>Monthly Statistics</h4>
            <p style={{ fontSize: '0.85rem', margin: '5px 0 0 0', color: 'var(--text-muted)' }}>Generate department statistics</p>
          </div>
        </div>

        <h3 style={{ marginTop: '2rem', fontSize: '1.1rem' }}>Recently Generated Reports</h3>
        
        <div className="table-container">
          <table className="data-table">
            <thead>
              <tr>
                <th>Report ID</th>
                <th>Type</th>
                <th>Related Case</th>
                <th>Generated By</th>
                <th>Date</th>
                <th>Action</th>
              </tr>
            </thead>
            <tbody>
              {loading ? (
                <tr>
                  <td colSpan="6" style={{ textAlign: 'center', color: 'var(--text-muted)', padding: '2rem' }}>
                    Loading reports...
                  </td>
                </tr>
              ) : reports.length > 0 ? (
                reports.map((r) => (
                  <tr key={r.ReportID}>
                    <td style={{ fontFamily: 'monospace' }}>{r.ReportNumber || `REP-${r.ReportID}`}</td>
                    <td><span className="badge badge-primary">{r.ReportType || 'MLR'}</span></td>
                    <td>{r.CaseNumber}</td>
                    <td>{r.GeneratedBy || `Dr. ${r.DoctorLastName || 'JMO'}`}</td>
                    <td>{r.Date || new Date(r.IssuedDate).toLocaleDateString()}</td>
                    <td>
                      <button className="btn btn-secondary" style={{ padding: '0.25rem 0.5rem', fontSize: '0.8rem' }}>
                        <ion-icon name="download-outline"></ion-icon> PDF
                      </button>
                    </td>
                  </tr>
                ))
              ) : (
                <tr>
                  <td colSpan="6" style={{ textAlign: 'center', color: 'var(--text-muted)', padding: '2.5rem' }}>
                    No generated reports in database yet. Click on a report type above to generate a new court report from your uploaded cases.
                  </td>
                </tr>
              )}
            </tbody>
          </table>
        </div>
      </div>
    </div>
  );
};

export default Reports;
